/**
 * famaly of services which enables to collect, process, and analyze streaming data in realtime
 * 24hrs, 7 days retention
 * data stored in shards
 *
 * streaming data ==> data generated by thousands of data sources, which tipically send in the
 * data records simultaneously and in small sizes
 *
 * kinesis streams ==> stream data and video to allow to build custom applications that process data in realtime
 *                 ==> Deals with datastream and video stream
 *
 * ---kinesis data firehose---
 * capture, transform, load data streams into aws data stores to enable near realtime analysis BI tooles
 *
 * -- kinesis data analytics ---
 * analyze, query and transform streamd data in realtime using standard SQL, stores the results in an aws data store
 *
 * --- shards ---
 *
 */
